environment:
  name: prod
  project: cdf-bootcamp-11-prod
  type: prod
  selected:
    - modules/

variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-11-prod # ex. cdf-bootcamp-01-test
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: https://westeurope-1.cognitedata.com
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      # Groups
      # OBJECT ID FOR PROD DATA DEVELOPER ENTRA GROUP
      data_developer_source_id: 5cca7696-b129-422f-b0f0-65a154cc85a1
      # OBJECT ID FOR PROD DATA PIPELINE OEE ENTRA GROUP
      data_pipeline_oee_source_id: 60e796f4-0040-4e75-b832-8179408c4daf
      # OBJECT ID FOR PROD ADMIN TK ENTRA GROUP
      readwrite_source_id: 6b67ee3f-643e-4353-a30c-1862b9d1601d
      # OBJECT ID FOR PROD ADMIN TK ENTRA GROUP
      readonly_source_id: 6b67ee3f-643e-4353-a30c-1862b9d1601d
      # OBJECT ID FOR PROD ADMIN TK ENTRA GROUP
      icapi_extractors_source_id: 67d59666-d0db-4ed2-b649-dff6790da87e
      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env

      icapi_ds_external_id: ds_icapi

      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
